package unit731.hunlinter;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;


public class LanguageChooserDialog extends javax.swing.JDialog{

	private static final long serialVersionUID = 1343230759230486883L;

	private final Consumer<String> onSelection;
	private boolean languageChosen;


	public LanguageChooserDialog(final List<String> availableLanguages, final Consumer<String> onSelection, Frame parent){
		super(parent, "Language chooser", true);

		Objects.requireNonNull(onSelection);

		initComponents();

		final DefaultListModel<String> model = new DefaultListModel<>();
		for(final String language : availableLanguages)
			model.addElement(language);
		languageList.setModel(model);

		this.onSelection = onSelection;
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      languageScrollPane = new javax.swing.JScrollPane();
      languageList = new javax.swing.JList<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setResizable(false);

      languageList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      languageList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
         public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            languageListValueChanged(evt);
         }
      });
      languageScrollPane.setViewportView(languageList);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(languageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(languageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void languageListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_languageListValueChanged
		languageChosen = true;
		onSelection.accept(languageList.getSelectedValue());

		dispose();
   }//GEN-LAST:event_languageListValueChanged

	public boolean languageChosen(){
   	return languageChosen;
	}


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JList<String> languageList;
   private javax.swing.JScrollPane languageScrollPane;
	// End of variables declaration//GEN-END:variables

}
